In [23]:
import pandas as pd
from functools import reduce
import numpy as np

In [24]:
# Load GO-Gene annotations
GO_annots = pd.read_csv("/space/grp/aadrian/Pseudobulk_Function_Pipeline_HighRes/bin/preprocessing/preprocessGO_pipe/data/2024_march/data/processing/bp_annotations_withGeneData_qc_annotations.csv")

# Differential expression analysis
dea = pd.read_csv("/space/grp/aadrian/Pseudobulk_Function_Pipeline_HighRes/bin/deconvolutingBulk/bin/notebooks/all_gene_marker_scores.csv", index_col=0)

# Calculates CTEs

In [30]:
def calc_unscaled_wilcox_minandmax(filtered_merged, gene)->float:
    """Calculate marker score for one gene in a GO term

    Args:
        filtered_merged (_type_): Df containing log fold changes for genes (hgnc_symbol)

    Returns:
        float: marker score
    """
    # For each gene, get the index of the largest log fold change
    max_gene_id = filtered_merged.scores.idxmax() 
    max_genes_df = filtered_merged.loc[max_gene_id,:] # df of the top single log fold changed genes
    
    is_max = filtered_merged.index.isin([max_gene_id]) # bool mask for if the gene is the max gene or not
    # Select rows that are not the maximum
    min_genes_df = filtered_merged.loc[~is_max] # df of the remaining, not max genes
    # lowest_value =abs(min_genes_df.loc[:,'logfoldchanges'].min())
    
    max_score = max_genes_df.loc['scores'] # max log fold change
    min_score = min_genes_df.loc[:,'scores'].mean() # mean of all of the log fold changes
    
    # marker_score = max_score/min_score
    return pd.DataFrame({'gene':[gene], "wilcox_max_score":[max_score], "wilcox_min_score":[min_score]})

def calc_unscaled_logfc_minandmax(filtered_merged, gene)->float:
    """Calculate marker score for one gene in a GO term

    Args:
        filtered_merged (_type_): Df containing log fold changes for genes (hgnc_symbol)

    Returns:
        float: marker score
    """
    # For each gene, get the index of the largest log fold change
    max_gene_id = filtered_merged.logfoldchanges.idxmax() 
    max_genes_df = filtered_merged.loc[max_gene_id,:] # df of the top single log fold changed genes
    
    is_max = filtered_merged.index.isin([max_gene_id]) # bool mask for if the gene is the max gene or not
    # Select rows that are not the maximum
    min_genes_df = filtered_merged.loc[~is_max] # df of the remaining, not max genes
    # lowest_value =abs(min_genes_df.loc[:,'logfoldchanges'].min())
    
    max_score = max_genes_df.loc['logfoldchanges'] # max log fold change
    min_score = min_genes_df.loc[:,'logfoldchanges'].mean() # mean of all of the log fold changes
    
    # marker_score = max_score/min_score
    return pd.DataFrame({'gene':[gene], "fc_max_score":[max_score], "fc_min_score":[min_score]})

def calc_max_difference_score(filtered_merged, gene)->float:
    """Calculate marker score for one gene in a GO term

    Args:
        filtered_merged (_type_): Df containing log fold changes for genes (hgnc_symbol)

    Returns:
        float: marker score
    """
    # For each gene, get the index of the largest log fold change
    filtered_merged = filtered_merged.sort_values('scores', ascending=False)
    
    ser_select = filtered_merged['scores'].iloc[0:2]
    
    diff_between_1rst_2nd = ser_select.iloc[0] - ser_select.iloc[1]
    print(ser_select.iloc[0])
    print(ser_select.iloc[1])
        
    return pd.DataFrame({"gene":[gene], "max_diff_score":[diff_between_1rst_2nd]})
    
def calc_unscaled_scores(df, gene):    
    lo_unscaled_scores = []
    
    lo_unscaled_scores.append(calc_unscaled_wilcox_minandmax(df, gene))
    lo_unscaled_scores.append(calc_unscaled_logfc_minandmax(df, gene))
    lo_unscaled_scores.append(calc_max_difference_score(df, gene))
    
    df_unscaled_scores = reduce(lambda left,right: pd.merge(left,right, on = 'gene', how = 'left'), lo_unscaled_scores)
    return df_unscaled_scores


def scale_one_marker_score_type(df_all_marker_scores, min_col, max_col):
    scalar = df_all_marker_scores.loc[:,min_col].min()

    df_all_marker_scores[f"{max_col}_scaled"] = df_all_marker_scores.loc[:,max_col] + abs(scalar)+1
    df_all_marker_scores[f"{min_col}_scaled"] = df_all_marker_scores.loc[:,min_col] + abs(scalar)+1
        
    return df_all_marker_scores
    

def scale_marker_scores(df_unscaled_scores):
    # Scale log2fcs
    df_scaled_scores = scale_one_marker_score_type(df_unscaled_scores, min_col = 'fc_min_score', max_col = "fc_max_score")
    # scale wilcoxon scores
    df_scaled_scores = scale_one_marker_score_type(df_unscaled_scores, min_col = 'wilcox_min_score', max_col = "wilcox_max_score")
    return df_scaled_scores

def calc_final_scores(df_scaled_scores):
    df_scaled_scores['wilcox_score'] = df_scaled_scores.loc[:,'wilcox_max_score_scaled']/df_scaled_scores.loc[:,'wilcox_min_score_scaled']
    df_scaled_scores['logfc_score'] = df_scaled_scores.loc[:,'fc_max_score_scaled']/df_scaled_scores.loc[:,'fc_min_score_scaled']
    return df_scaled_scores

def calc_all_gene_enrichment_scores(df_all_scores:pd.DataFrame):
    lo_unscaled_scores = []
    for gene, df in df_all_scores.groupby("names"):
        # Calculate unscaled MGC scores        
        df_one_unscaled_scores = calc_unscaled_scores(df=df, gene=gene)
        lo_unscaled_scores.append(df_one_unscaled_scores)
    # concat all the unscaled scores
    df_unscaled_scores = pd.concat(lo_unscaled_scores, axis = 0)

    return df_unscaled_scores
    
dea_scored = calc_all_gene_enrichment_scores(dea)
dea_scored.head()

6.8800364
-0.5030107
7.3830471
1.4524969
-0.2201268
1.6726237000000002
13.936005
7.96195
5.974055
11.515552
0.076370016
11.439181984
3.3583012
-0.5080346
3.8663358
0.90818
0.322585
0.585595
0.07198619
-0.019043228
0.091029418
15.734682
-2.1600392
17.8947212
99.76272
-14.076869
113.839589
0.11606443
-0.022916425
0.138980855
0.020597452
-0.001295832
0.021893284
0.09899286
-0.012910662
0.111903522
0.25023758
-0.029371757
0.279609337
25.3218
-4.2721715
29.5939715
56.170017
-10.160558
66.330575
49.457413
-4.815096
54.272509
3.8319995
-0.7495667
4.5815662
13.8606205
-4.91557
18.7761905
3.024899
-0.48382708
3.50872608
9.956351
-2.9824321
12.9387831
3.3746936
-0.6219712
3.9966648
16.400284
1.3942494
15.0060346
5.904799
0.35867682
5.546122179999999
13.932295
-2.724465
16.65676
28.168686
-7.0615616
35.2302476
36.906796
18.090712
18.816084
32.518723
-6.3378315
38.8565545
44.748207
2.9806082
41.7675988
90.17977
-2.213177
92.392947
38.41523
5.4597282
32.9555018
26.306557
8.549136
17.757421
3.312342
-0.7657933
4.0781353000000005
1.4152702
-0.29855907
1.71382927
67.2727
7.2907786
59.9819214
28.824324
-7.0378942
35.8622182
0.81469333
0.45877528
0.35591805
50.23192
-10.886923
61.118843
15.837893
11.644183
4.193709999999999
27.326433
-5.5785975
32.9050305
74.018456
3.545067
70.473389
18.7914
9.878065
8.913335
33.467167
3.4889653
29.978201700000003
7.13795
4.8422303
2.2957197000000003
3.9575062
-0.34120795
4.29871415
1.5284908
0.07259999
1.4558908099999999
1.5375813
-0.31681705
1.85439835
28.641747
-4.473469
33.115216
21.395283
-5.60613
27.001413
16.658377
-4.4781256
21.1365026
42.651875
-12.895474
55.547349
18.34774
1.4071643
16.9405757
26.828842
-5.5052705
32.3341125
0.6022603
0.22388697
0.37837332999999995
29.788374
-2.1667318
31.955105800000002
1.3055316
-0.40471074
1.71024234
18.168718
-1.159848
19.328566
33.795795
7.1210732
26.6747218
25.928116
-2.6311927
28.5593087
2.456371
-0.12854941
2.58492041
49.02843
-6.9410987
55.9695287
55.539577
6.6881533
48.8514237
0.42503256
0.17166586
0.2533667
29.194508
-2.7155993
31.9101073
20.99086
-0.7153852
21.7062452
10.645685
2.779895
7.8657900000000005
13.740139
-1.8919059
15.632044899999999
11.589702
-3.4033647
14.9930667
20.387716
-5.300304
25.68802
4.301987
2.3812857
1.9207012999999997
2.9480608
1.6639367
1.2841240999999999
6.2882457
3.64015
2.6480957
7.957422
-0.038200855
7.995622855000001
20.923891
-2.675412
23.599303000000003
12.227138
-1.8626858
14.0898238
0.39476353
0.387783
0.006980529999999985
21.360079
-5.2244234
26.584502399999998
19.400398
-2.3326757
21.7330737
9.790597
0.7424416
9.0481554
48.949657
-3.6959999
52.6456569
37.562344
-6.7626257
44.324969700000004
0.8076111
0.3493394
0.4582717

15.061642
-3.397709
18.459351
0.5215828
0.22789277
0.29369003000000005
15.876239
-4.3503346
20.226573600000002
0.026911413
-0.0016138328
0.028525245799999998
15.250196
5.5185876
9.7316084
20.124052
18.021645
2.1024069999999995
20.056753
-5.4692497
25.5260027
12.751801
9.836358
2.915443
20.455627
17.536676
2.918951
16.256977
-1.7716175
18.0285945
2.2283726
0.022704141
2.205668459
24.253439
-7.816093
32.069532
15.5680895
-0.7359594
16.304048899999998
37.387802
-8.036972
45.424774
42.815434
18.87644
23.938994000000005
98.324356
-7.9000936
106.2244496
0.25600207
0.17182694
0.08417513000000001
16.238192
0.9596818
15.278510200000001
31.987429
-7.3052077
39.2926367
9.142771
-2.6153042
11.7580752
57.298527
-4.749593
62.04812
73.84885
35.67295
38.1759
71.882286
-18.051058
89.93334399999999
13.381231
1.8953656
11.4858654
18.769207
-0.876695
19.645902000000003
49.652752
8.20746
41.445292
0.75174373
-0.077057496
0.8288012260000001
34.65019
-4.775951
39.426141
7.9839783
-1.4823415
9.4663198
31.357208
-6.8070297
38.1642377
10.537398
-2.0940373
12.6314353
71.05235
-6.469385
77.521735
26.498446
3.9822357
22.5162103
144.44684
-7.287621
151.734461
26.399408
-4.647437
31.046845
8.818339
0.16907348
8.64926552
41.54332
-3.883611
45.426931
17.361006
2.4476037
14.9134023
8.79852
-2.507265
11.305785
43.54498
-6.8995495
50.4445295
11.147722
0.33114502
10.81657698
41.17643
-0.26364875
41.440078750000005
36.918957
-8.651928
45.570885
3.4050217
-0.014766564
3.4197882639999997
14.279864
4.108745
10.171119000000001
40.77164
9.652904
31.118736
11.642687
-0.99017876
12.632865760000001
6.7358446
-0.051168937
6.787013537
11.34011
-0.4862663
11.8263763
58.891937
0.43851614
58.45342086
19.269896
-0.8462133
20.116109299999998
17.14671
-4.5801578
21.7268678
21.936014
-6.341271
28.277285
11.036652
-3.628871
14.665523
7.285459
5.523356
1.7621030000000006
24.777319
-6.487657
31.264975999999997
5.4938235
0.084690645
5.409132855
7.8921223
-0.5443168
8.4364391
6.295203
-1.2838966
7.5790996
13.206418
-2.8420608
16.048478799999998
21.959917
-1.6628789
23.6227959
1.971707
-0.45477808
2.42648508
9.214498
-1.4417982
10.6562962
51.310566
-3.8670244
55.1775904
48.017105
8.280056
39.737049
9.813648
-1.7230593
11.5367073
13.334393
-3.77041
17.104803
9.99159
-1.8168529
11.808442900000001
6.8128495
0.5635832
6.2492662999999995
5.541701
3.2447343
2.2969666999999996
2.1590757
-0.11549102
2.2745667199999997
5.9841986
2.1655452
3.8186534
21.129284
-3.9574986
25.0867826
41.48737
-7.99295
49.48032
12.148233
4.4301987
7.718034299999999
0.28088257
-0.060680114
0.341562684
26.536701
-5.774719
32.31142
32.75044
15.490734
17.259705999999998
0.7229752
0.13081264
0.59216256
11.800701
-3.669251
15.469952
7.073373
-1.409991
8.483364
5.7716503
-0.4794641
6.2511144000000005
6.769987
-1.6009221
8.3709091
26.29211
-4.9347005
31.2268105
20.950026
-5.552203
26.502229
4.3705115
1.8035223
2.5669892
19.789547
-4.767296
24.556843
1.9376103
1.2144828
0.7231274999999999
16.923006
-5.168947
22.091953
5.841277
-1.2675043
7.1087812999999995
21.154013
-6.1938167
27.3478297
6.6276484
0.15104637
6.47660203
2.465774
0.23673883
2.22903517
0.32162008
-0.03776369
0.35938377
0.114299506
0.042714167
0.071585339
8.880518
4.421376
4.459142
3.9365525
0.17307337
3.76347913
0.45615992
-0.03330596
0.48946588
0.36998206
-0.02797792
0.39795998
3.4598153
-0.6600576
4.1198729
22.025375
5.403765
16.62161
2.6363246
-0.74446464
3.38078924
5.226884
2.00021
3.226674
19.608227
-3.279795
22.888022
11.434842
8.81019
2.6246519999999993
41.52681
2.1266842
39.4001258
13.307119
-4.8772225
18.184341500000002
3.7027948
1.0248303
2.6779645
57.53733
13.160616
44.376714
2.4241362
-0.30670527
2.73084147
0.8131408
-0.020036638
0.833177438
0.3254661
-0.044219017
0.36968511699999995
0.5501368
-0.14383635
0.6939731499999999
4.1039705
-0.67716426
4.78113476
0.7786302
0.21279609
0.5658341100000001
10.923567
-2.053118
12.976685
30.561678
10.5869055
19.9747725
15.960194
10.210177
5.750017
20.393148
2.4206288
17.9725192
1.7565321
-0.32663977
2.08317187
17.308142
1.7341284
15.5740136
34.100456
27.568716
6.531740000000003
1.1258867
-0.13685302
1.26273972
3.8106594
-0.3871007
4.1977601
0.4495421
0.17499086
0.27455124
0.111370005
0.015673708
0.09569629699999999
1.8024926
1.4502162
0.3522763999999998
38.052418
-9.207509
47.259927000000005
0.0665704
0.01825992
0.04831048
2.331541
-0.22755043
2.55909143
0.88898766
0.6738337
0.21515395999999998
147.165
-10.687565
157.852565
86.01341
14.769406
71.24400399999999
0.50597453
-0.014090414
0.520064944
71.05358
-4.2676625
75.3212425
24.695362
-8.199128
32.89449
18.809822
-6.0228066
24.8326286
45.059006
-9.967036
55.026042
83.54393
-5.5395575
89.0834875
19.644674
-3.0253444
22.670018399999996
56.927647
-11.431058
68.358705
16.92343
12.637468
4.285962
6.6600466
-1.1225146
7.7825612
18.601242
-4.3974843
22.9987263
9.549675
-3.0438986
12.593573600000001
0.115560144
-0.012265129
0.12782527300000002
0.902512
-0.14104898
1.04356098
27.512636
-1.7958812
29.3085172
40.348785
-8.835068
49.183853
41.978245
-0.7057046
42.6839496
24.034325
-1.5053765
25.5397015
6.4693065
2.3781626
4.0911439000000005
2.5315158
0.15650448
2.37501132
1.3362776
-0.011556807
1.3478344070000001
9.2272835
-1.5060629
10.7333464
44.048294
-10.12074
54.169033999999996
3.674811
0.39174178
3.2830692200000002
1.7143581
1.1438746
0.5704835000000001
0.12943524
0.066908255
0.06252698500000001
4.3140187
-0.18662812
4.50064682
19.494463
-4.876658
24.371121
40.607475
15.803034
24.804441
90.2804
-12.800641
103.081041
9.895103
5.8515296
4.0435734000000005
8.551628
-2.2352211
10.7868491
64.66667
-9.286395
73.953065
2.3896346
-0.32760805
2.7172426499999998
39.55181
-7.9279065
47.4797165
0.30035764
-0.08682421
0.38718185
46.86562
-10.324949
57.190568999999996
2.1828244
-0.34568298
2.5285073799999997
18.382019
11.681179
6.7008399999999995
142.01425
-15.819527
157.833777
15.081829
8.666542
6.415287000000001
4.242942
-0.3692036
4.6121456
46.156418
-9.619924
55.776342
18.410114
0.68084955
17.72926445
6.8730063
-0.88922185
7.76222815
10.041421
-1.8627821
11.9042031
47.240173
-9.341074
56.581247
0.5850926
-0.07068588
0.6557784799999999
7.264378
2.2778265
4.986551499999999
33.351883
-3.9679701
37.3198531
4.568913
2.2594879
2.3094251000000003
21.433323
-5.1015487
26.534871700000004
15.707614
0.023294104
15.684319896
5.0451903
-0.40474927
5.44993957
99.26255
-7.0924516
106.35500160000001
104.92618
17.638735
87.287445
2.9722447
2.4353085
0.5369362
39.50949
-12.547537
52.057027
48.062824
-5.4763756
53.539199599999996
27.79971
-0.44893345
28.24864345
94.48092
-6.876368
101.357288
20.77174
-0.015494401
20.787234401000003
29.254904
0.38741836
28.867485639999998
44.116577
9.830192
34.286384999999996
1.8546654
0.59242374
1.26224166
33.79648
-2.5938613
36.3903413
22.021685
7.4300833
14.591601700000002
116.829544
-11.028945
127.85848899999999
13.667199
-1.1356293
14.8028283
34.77143
-5.840888
40.612318
1.1870173
-0.0016767542
1.1886940542
0.6631323
0.34136587
0.32176643
18.771734
-2.5514257
21.323159699999998
3.5727818
1.643081
1.9297008
12.302289
5.989297
6.312992
39.020924
-6.672296
45.693220000000004
86.77361
28.218565
58.55504500000001
10.866928
-3.1046593
13.9715873
21.321827
-4.0823007
25.4041277
10.771933
-3.726122
14.498055
12.241952
-2.5254397
14.7673917
13.610003
-3.7739007
17.3839037
68.947235
-10.951319
79.898554
25.69459
-4.4686837
30.1632737
24.927975
21.76463
3.1633449999999996
37.622772
-10.22241
47.845181999999994
1.3317541
0.52365047
0.80810363
11.544279
-1.2935879
12.8378669
20.884838
-6.049976
26.934814
22.397217
3.0591187
19.338098300000002
148.96394
5.5005307
143.4634093
68.03626
-12.591686
80.627946
48.123272
-3.1820047
51.3052767
84.87283
0.5360175
84.3368125
9.899775
9.466346
0.4334290000000003
68.36849
-15.682241
84.050731
59.25657
31.74558
27.510990000000003
3.222585
-0.31959188
3.54217688
30.435663
-5.2471123
35.6827753
15.523448
-1.1204721
16.6439201
20.516357
4.9243197
15.5920373
54.26978
-0.96659756
55.236377559999994
127.74215
-10.4628525
138.2050025
135.44643
-14.937265
150.383695
1.9221296
1.3578035
0.5643261000000002
0.30476257
0.020061431
0.284701139
1.8724182
-0.32158095
2.19399915
3.4062524
0.3503752
3.0558772000000003
2.7644467
-0.6973251
3.4617718
2.1371305
0.91633034
1.22080016
0.32090205
-0.047446683
0.368348733
4.868298
-0.6629894
5.5312874
2.618453
-0.22367723
2.84213023
30.645151
3.8089907
26.8361603
16.265738
11.0648
5.200937999999999
7.472389
-0.9042905
8.3766795
0.40676042
0.0181555
0.38860492
0.61830807
-0.08359654
0.7019046099999999
1.1578119
0.09947114
1.05834076
16.553226
0.28684312
16.26638288
0.8123372
-0.13491642
0.94725362
42.45241
-10.238209
52.690619
81.967415
-18.041578
100.008993
20.50563
6.0169764
14.4886536
4.2730103
2.5269234
1.7460869000000003
80.69695
39.883785
40.813165
0.051262796
-0.0061325645
0.0573953605
0.11783227
0.027476903
0.090355367
0.91597813
-0.08320497
0.9991831
0.26818356
0.08924897
0.17893459
27.90102
-1.9203398
29.8213598
0.22602525
-0.044541784
0.27056703400000004
0.15810397
-0.039054755
0.197158725
7.086683
6.1740313
0.9126516999999996
8.869379
-2.56572
11.435099000000001
0.14670445
-0.01968876
0.16639320999999999
0.45212427
-0.07229971
0.52442398
16.145676
-4.4474454
20.5931214
49.714413
-0.28743568
50.00184868
0.83772516
0.74778587
0.08993929
4.9992104
1.8723522
3.1268582
38.4089
-0.48411292
38.893012920000004
8.709232
1.2961636
7.4130684
0.32631144
-0.014506609
0.340818049
23.663424
0.56993645
23.09348755
15.013159
-4.401368
19.414527
21.079025
-4.1660967
25.245121700000002
71.50586
0.20577042
71.30008958
3.0058486
1.2010425
1.8048061000000002
4.538415
3.2529523
1.2854626999999996
0.40223297
0.120095454
0.28213751600000003
16.899008
-2.659264
19.558272
9.413445
-2.3595147
11.7729597
5.5898476
-1.4424255
7.032273099999999
101.45233
7.4691935
93.9831365
66.98222
-10.171423
77.153643
4.70632
-1.1403342
5.8466542
4.772577
-1.431147
6.203724
0.16275337
0.04666075
0.11609262000000001
5.6969376
-0.4740734
6.171011
55.523796
-3.6001046
59.1239006
1.8115313
0.32377088
1.4877604199999999
2.2858555
-0.1081268
2.3939823
11.691469
-2.3348596
14.0263286
21.74452
-4.5835953
26.3281153
2.9790971
2.0422542
0.9368429000000003
26.245266
15.361916
10.88335
43.78662
-3.1214755
46.9080955
5.605464
1.7312123
3.8742516999999994
18.521181
-0.41337788
18.934558879999997
33.57784
-7.128894
40.706734000000004
132.34566
5.0556045
127.29005550000001
11.505821
-0.23231484
11.73813584
13.8682995
2.6271675
11.241131999999999
4.466909
0.89860046
3.5683085400000003
59.41093
6.0829277
53.3280023
115.24839
-7.3378773
122.5862673
121.14933
-12.744348
133.893678
37.62775
-7.452644
45.080394
10.814084
8.360623
2.453460999999999
7.7991714
6.7301416
1.0690298
0.025199575
-0.0032276656
0.028427240599999997
21.68306
17.890724
3.7923360000000024
1.1231271
-0.10102593
1.22415303
37.54012
-8.2641535
45.8042735
12.695902
1.8763064
10.8195956
75.23752
41.12444
34.113080000000004
58.233295
-8.296962
66.530257
42.327274
-9.884953
52.212227
25.894083
-6.593608
32.487691
13.497165
-3.1475043
16.6446693
39.974
-7.690843
47.664843
8.878126
-0.00022898102
8.87835498102
1.9655093
-0.07392299
2.0394322899999997
41.695793
-8.928526
50.624319
178.34915
-21.799543
200.148693
10.805718
-2.9653096
13.7710276
0.7400558
0.70079595
0.039259850000000096
73.07769
-0.5595178
73.6372078
18.037092
-2.0294893
20.066581300000003
17.470724
-5.454336
22.925060000000002
27.237274
-7.8277984
35.0650724
15.081578
2.71302
12.368558
4.3093624
-0.7922827
5.101645100000001
7.7592273
3.267485
4.4917423
21.844193
-5.579427
27.42362
7.235082
-2.846397
10.081479
12.45861
2.96773
9.49088
16.004538
0.59852123
15.40601677
10.123398
0.014080168
10.109317832
2.758986
-0.50103486
3.26002086
16.315165
0.82293254
15.49223246
45.919308
-3.0837703
49.0030783
17.31142
-4.7092223
22.0206423
9.18513
1.9534616
7.231668399999999
0.11891508
-0.035504322
0.154419402
0.39424896
-0.12426513
0.51851409
71.3284
-5.7692103
77.0976103
0.43981612
-0.06261671
0.5024328299999999
19.09538
2.1469584
16.9484216
46.635883
12.872936
33.762947
0.21781123
0.16474745
0.053063780000000005
0.033294737
-0.002259366
0.035554103
2.763101
0.6354054
2.1276956
0.42304486
-0.04328145
0.46632631
36.791245
-8.852998
45.644243
17.501995
-4.13696
21.638955000000003
22.992434
15.080933
7.9115009999999995
39.123123
28.190792
10.932331000000001
45.346027
-6.4399986
51.7860256
19.34479
15.713157
3.631632999999999
8.384938
3.3160057
5.0689323
25.979221
-3.1507733
29.1299943
18.694588
-6.8745136
25.5691016
17.49526
-3.4630733
20.9583333
19.868681
-5.411032
25.279712999999997
3.6728132
-0.2866167
3.9594299
0.09562543
-0.017106628
0.112732058
8.722647
-0.68489295
9.40753995
0.95994306
0.07954666
0.8803964
14.279787
1.6296885
12.6500985
12.659635
-4.4679418
17.1275768
25.885374
-3.2756503
29.161024299999998
33.390938
9.558649
23.832288999999996
42.02748
-8.24099
50.26846999999999
1.0111194
0.011629541
0.9994898589999999
10.946539
-4.2177925
15.1643315
8.643703
-2.8899221
11.5336251
5.3484173
-1.7458508
7.094268100000001
0.9831932
-0.0927858
1.075979
6.9712143
-0.2822987
7.253513
34.040737
-8.617202
42.657939
0.05405167
-0.015170028
0.069221698
0.1282928
0.0899195
0.03837330000000001
15.158819
-3.3016171
18.4604361
10.634732
-0.39370143
11.02843343
62.371304
-1.1272805
63.4985845
50.577343
1.7110039
48.8663391
123.18607
43.748955
79.437115
19.235027
-5.490159
24.725186
5.36656
-1.0935332
6.460093199999999
9.42262
-2.0987647
11.5213847
21.290571
-7.97055
29.261121
37.153957
-1.48634
38.640297
24.673979
-6.8805532
31.554532199999997
18.817314
-5.7494245
24.5667385
19.8815
-3.2900827
23.1715827
104.191826
-4.5752873
108.7671133
99.32961
11.58321
87.74640000000001
1.792623
-0.118395306
1.911018306
1.4683955
-0.16346282
1.63185832
1.1531463
0.87426734
0.27887896
62.123844
-6.253925
68.377769
54.011913
25.506422
28.505491
48.341663
6.744671
41.596992
21.567513
-5.4472446
27.014757600000003
53.301605
-11.209375
64.51098
44.428825
1.8664889
42.5623361
9.576712
-1.8372011
11.4139131
36.70714
-6.508904
43.216044000000004
24.51428
-4.3208838
28.8351638
17.674067
1.474561
16.199506
1.13446
-0.090168685
1.224628685
19.315557
-1.6139661
20.929523099999997
14.610242
-4.0446777
18.6549197
0.08385928
-0.014201729
0.09806100899999999
0.04944756
0.008383747
0.041063813000000005
9.846619
-0.2725322
10.119151200000001
1.9463006
1.0188395
0.9274611000000001
3.1999538
0.978153
2.2218007999999996
0.02641717
-0.0071008643
0.0335180343
1.1527009
-0.16868487
1.32138577
0.40609938
-0.1090951
0.51519448
9.214392
-1.4665858
10.6809778
19.550472
-3.563897
23.114369
12.092758
-1.9577461
14.0505041
7.2590528
-1.0017321
8.2607849
8.839798
-1.410458
10.250256
6.6429434
-1.7931867
8.4361301
36.093613
-3.3846762
39.4782892
116.93271
0.032880437
116.899829563
20.87957
-7.8157873
28.6953573
13.984772
-3.9838402
17.9686122
12.511743
-2.3592293
14.870972299999998
0.19548808
-0.023884725
0.219372805
0.5380759
0.01721167
0.52086423
70.93126
21.628729
49.302530999999995
3.646746
-0.2981544
3.9449004
28.722864
-4.074433
32.797297
14.919993
3.665896
11.254097
8.214617
0.110967465
8.103649535
10.710884
5.024673
5.686211
2.1514614
-0.36806542
2.5195268200000003
15.206808
7.8640065
7.3428015
24.276556
-4.9361086
29.2126646
9.905338
0.5915077
9.313830300000001
0.26078597
-0.027435157
0.28822112699999997
51.3692
-7.88152
59.25072
2.2283063
0.13406856
2.0942377399999996
0.13040958
-0.027435157
0.157844737
3.937816
0.747584
3.190232
30.199081
-7.941228
38.140309
7.85515
-0.5859527
8.4411027
5.960026
4.4114356
1.5485904000000001
25.354362
-6.402454
31.756815999999997
2.2229676
1.4616749
0.7612927
8.205993
5.8814106
2.3245823999999997
2.5866215
-0.25111237
2.83773387
44.211582
6.0331516
38.178430399999996
7.1131234
-2.0267284
9.1398518
2.7823436
-0.5758913
3.3582349
7.0807385
-1.4856045
8.566343
21.112188
-2.69781
23.809998
7.4093833
3.6534305
3.7559528
34.866432
-4.619742
39.486174000000005
29.650476
-7.637394
37.28787
3.08348
-0.42220598
3.50568598
15.15684
-2.9509327
18.1077727
10.885438
-2.1998034
13.085241400000001
13.143955
-2.6555464
15.7995014
23.645039
-5.965097
29.610136
34.66169
-7.2232666
41.8849566
10.713865
3.3824213
7.3314437
129.99745
18.708883
111.28856699999999
4.958608
-0.27854756
5.23715556
2.5414884
-0.3463055
2.8877939
22.179024
-4.8375444
27.016568399999997
6.8417187
-1.1184955
7.9602142
22.75951
-5.6840386
28.4435486
7.566026
-2.5851176
10.1511436
18.117348
-6.8323565
24.9497045
19.190548
-3.6950188
22.8855668
0.8448005
0.41631237
0.42848812999999997
21.870325
-4.770375
26.640700000000002
3.7487888
-0.38441497
4.13320377
35.353977
-7.638633
42.99261
3.1388445
-0.25236133
3.3912058299999996
3.0197408
-0.3947435
3.4144843000000002
4.86946
-0.41346395
5.28292395
1.2904534
-0.102639765
1.393093165
10.401109
3.578513
6.822596
1.2277366
1.1405629
0.08717370000000013
3.8210576
-0.66748124
4.48853884
26.708841
5.5661993
21.1426417
3.4964259
-0.5348242
4.0312501
5.271728
-0.44107416
5.712802160000001
4.380293
1.2943693
3.0859237
0.003697514
0.0023937118
0.0013038021999999998
66.33149
-13.4612055
79.79269550000001
33.938187
-1.9204899
35.8586769
0.1344093
-0.010005764
0.144415064
0.096314505
0.03314313
0.063171375
0.7832708
0.64470613
0.13856467000000006
4.1679406
-0.50505257
4.67299317
1.1338102
-0.08675355
1.2205637500000002
0.08687543
0.019679235
0.067196195
10.349756
-4.120066
14.469821999999999
18.080437
4.368345
13.712092
3.136771
0.2740014
2.8627696
6.498086
-0.639248
7.137334
0.021654962
-0.0067780977
0.0284330597
0.35212028
-0.06197118
0.41409146
0.7701116
0.20746753
0.5626440699999999
59.269627
4.282874
54.986753
17.531408
-3.445533
20.976941
12.820377
-2.9895475
15.809924500000001
33.3162
-1.8580852
35.1742852
0.18505743
-0.029371757
0.214429187
12.788097
-1.6625412
14.4506382
13.715469
-0.7670828
14.482551800000001
0.37269187
-0.043083373
0.41577524299999996
20.36386
12.044592
8.319268
22.183592
-4.376657
26.560249
0.66690505
-0.050495435
0.717400485
12.000194
2.4933696
9.506824400000001
35.761044
5.5104012
30.250642799999998
64.28143
-5.116354
69.397784
14.408931
-0.24006774
14.648998740000001
2.0914838
0.69659007
1.3948937299999997
8.047777
2.5429943
5.5047827
23.70079
23.235983
0.4648070000000004
60.973072
-12.999193
73.97226500000001
16.500803
-3.3594651
19.860268100000003
0.10112054
-0.0077463975
0.1088669375
0.006632906
-0.0010556258
0.0076885318000000005
0.019025564
-0.0012910663
0.0203166303
5.7586274
-0.68587893
6.44450633
52.16723
-11.317887
63.485117
12.065103
8.773067
3.2920360000000013
34.051865
30.476526
3.5753389999999996
25.610283
-9.255614
34.865897
29.353725
-7.0991225
36.452847500000004
13.944449
-3.1957855
17.140234500000002
8.911939
-2.7023537
11.6142927
14.005051
-3.339626
17.344677
10.005755
1.3112626
8.694492400000001
4.80695
-0.8807449
5.687694899999999
15.720692
-4.224064
19.944755999999998
21.874468
7.7798367
14.0946313
40.68989
-7.2643175
47.954207499999995
17.821167
2.2865653
15.5346017
41.80004
-6.8915596
48.6915996
34.945488
3.9653559
30.9801321
27.087221
-3.8509057
30.938126699999998
0.16780362
-0.050351582
0.218155202
22.784765
-2.9944036
25.7791686
6.321029
5.500792
0.8202370000000005
0.15107754
0.0053276275
0.14574991250000002
13.085286
0.77219695
12.31308905
9.500728
-0.78806263
10.288790630000001
3.3218913
-0.4816939
3.8035851999999997
0.26187837
0.15066591
0.11121246000000004
0.34788767
-0.08311467
0.43100234
0.051423132
-0.009682997
0.061106129
163.47842
-9.23298
172.7114
69.487045
9.206046
60.280998999999994
42.080513
2.2354262
39.845086800000004
16.345303
0.16152321
16.183779790000003
60.14745
15.011317
45.136133
21.91023
-2.6477456
24.5579756
5.064942
-0.7782191
5.8431611000000006
50.47685
9.724955
40.751895
24.620861
-5.874344
30.495205000000002
40.28465
6.4177766
33.8668734
13.790395
-2.7616174
16.5520124
57.789673
23.116789
34.672883999999996
3.4159565
-0.21591856
3.63187506
2.6086335
-0.72200954
3.33064304
34.47905
-6.148112
40.627162
10.39843
-3.0793214
13.477751399999999
72.75389
-11.899726
84.653616
5.6307845
-0.32626596
5.95705046
0.15253922
-0.017429395
0.169968615
20.681273
10.6459675
10.035305500000002

,gene,wilcox_max_score,wilcox_min_score,fc_max_score,fc_min_score,max_diff_score
0,A1BG,6.880036,-2.270726,0.879714,-11.890932,7.383047
0,A1CF,1.452497,-0.530261,1.082467,-11.338889,1.672624
0,A2M,13.936005,-1.451539,7.711000,-0.801732,5.974055
0,A2ML1,11.515552,-4.485514,0.799550,-7.422299,11.439182
0,A3GALT2,3.358301,-1.241936,1.106296,-16.601308,3.866336

# Calculate MGC Scores

In [26]:
def calc_wilcox_MGC(df_all_marker_scores_filtered):
    return np.mean(df_all_marker_scores_filtered['wilcox_max_score'])
def calc_logfc_MGC(df_all_marker_scores_filtered):
    return  np.mean(df_all_marker_scores_filtered['fc_max_score'])
def get_diff_MGC(df_all_marker_scores_filtered):
    return np.mean(df_all_marker_scores_filtered.loc[:,'max_diff_score'])

def calc_all_MGC_for_go_term(go_term, go_annot, dea):
    # Filter df for genes in GO term
    go_annot_filtered = go_annot[go_annot.loc[:,"GO ID"] == go_term]
    # get genes
    lo_genes_in_go_term = go_annot_filtered.DB_Object_Symbol
    
    # Get marker gene scores for the genes
    df_all_marker_scores_filtered = dea[dea.loc[:,'gene'].isin(lo_genes_in_go_term)]
    
    # Calc MGC types
    wilcox_MGC = calc_wilcox_MGC(df_all_marker_scores_filtered)

    # lofgc MGC
    logfc_MGC = calc_logfc_MGC(df_all_marker_scores_filtered)
    # max diff between 1rst and second MGC
    diff_MGC = get_diff_MGC(df_all_marker_scores_filtered)
    
    ser_MGC = pd.Series([go_term, wilcox_MGC, logfc_MGC, diff_MGC], index = ['id', 'wilcox_MGC', 'logfc_MGC', 'diff_MGC'])
    
    return ser_MGC
    
def calc_all_marker_scores(go_annot:pd.DataFrame, dea:pd.DataFrame) -> pd.DataFrame:
    """wrapper function to calculate the marker scores for each go term
    
    marker score is how much a GO term has genes has pseud-marker genes

    Args:
        enrichment_master (pd.DataFrame): dataframe that has all of our enriched GO terms
        go_annot (pd.DataFrame): df that tells us what genes are affiliated with each go term
        df_all_scores (pd.DataFrame): df contianing wilcoxon tests for 1 vs all for each cell type and each gene


    Returns:
        pd.DataFrame: _description_
    """
    lo_go_terms = go_annot.loc[:,'GO ID'].unique()
    lo_MGC_for_go_term = []
    for go_term in lo_go_terms:
        ser_MGC = calc_all_MGC_for_go_term(go_term=go_term, go_annot=go_annot, dea=dea)
        lo_MGC_for_go_term.append(ser_MGC)
            
    return pd.concat(lo_MGC_for_go_term, axis = 1).T

mgcs = calc_all_marker_scores(go_annot=GO_annots,
                            dea=dea_scored)
mgcs.head()

           id wilcox_MGC logfc_MGC   diff_MGC
0  GO:0000045  22.131554  1.317919  25.622232
1  GO:0000070  13.388181   1.29324  14.892069
2  GO:0000077  20.420476  1.287744  23.342727
3  GO:0000079  19.141894  1.487674  20.550454
4  GO:0000082  30.492923  1.632122  32.970738

In [27]:
mgcs.to_csv("data/brain_mgcs.csv")